// Fetch handlers
export const FETCH_BAR_CHART_DATA = "FETCH_BAR_CHART_DATA";

// app handlers
export const UPDATE_INITIAL_BAR_DATA = "UPDATE_BAR_CHART_DATA";
export const ADD_SELECTED_COUNTRY = "ADD_SELECTED_COUNTRY";
export const DELETE_SELECTED_COUNTRY = "DELETE_SELECTED_COUNTRY";
export const CHANGE_CHART = "CHANGE_CHART";
export const CHANGE_FETCHING = "CHANGE_FETCHING";
